databases:
  - name: hrmslite-db
    plan: free

services:

  # Backend (Django)
  - type: web
    name: hrmslite-api
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hrmslite-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "hrmslite-api.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://hrmslite-frontend.onrender.com"

  # Frontend (React/Vite)
  - type: web
    name: hrmslite-frontend
    env: static
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
    envVars:
      - key: VITE_API_URL
        value: "https://hrmslite-api.onrender.com/api/"
